[package]
name = "rodos_can_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "0.4.0", features = [ "defmt", "stm32g0b1ke" ]  }

defmt = "1.0"

heapless = { version = "0.9", default-features = false }

embedded-can = "0.4.1"

[profile.release]
debug = 2
