[package]
name = "rodos_can_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "0.2.0" }

defmt = "0.3"

heapless = { version = "0.8", default-features = false }

embedded-can = "0.4.1"

[profile.release]
debug = 2
